"""add Department

Revision ID: 79acc815ea7d
Revises: 35d612fc6ead
Create Date: 2025-03-30 09:24:11.377409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79acc815ea7d'
down_revision = '35d612fc6ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
